on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: A job to run JMeter script
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: docker pull egaillardon/jmeter       
      - name: Run Container
        with:
          test-plan-name: T01_HomePageLoad.jmx
        run: |
          docker run --interactive --rm --volume `pwd`:/jmeter egaillardon/jmeter --nongui --testfile {{ inputs.test-plan-name }} --logfile result.jtl                  
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
