on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run JMeter script
    steps:
      # To use this repository's private action,
      # you must check out the repository 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: docker pull egaillardon/jmeter       
      - name: Run image
        run: |
          docker run --interactive --rm --volume `pwd`:/jmeter egaillardon/jmeter --nongui --testfile T01_HomePageLoad.jmx --logfile result.jtl
          cat result.jtl                   
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl